server :
  port : 8080
spring:
  output:
    ansi:
      enabled : always
  redis:    # user정보도 redis에 저장됨..
    host: localhost
    port: 6379

  jpa :
    hibernate :
      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        format_sql : true
        default_batch_fetch_size : 100
    open-in-view: false

  devtools:   # 정적자원 캐시사용안함=> 새로고침시 바로바로,   but 실제서버운영시 캐시 사용해야된다
    livereload :
      enabled : true
    freemarker:
      cache: false
    restart:
      enabled: false
  thymeleaf:
    cache: false

